"""
Era configuration reference — NOT imported by the bot.
Use this to manually revert to any era's config by copying values
into simple_15min_trader_enhanced_fixed.py.

To rollback:
  1. git stash (save current changes)
  2. Copy desired era's values into the main config
  3. Restart bot
  4. If bad: git stash pop (restore previous state)
"""

ERA_CONFIGS = {
    'era2': {
        'description': 'Most profitable era: +$46.80, $2.04/hr, 47.3% WR',
        'MIN_CONVICTION_THRESHOLD': 0.01,
        'MIN_ENTRY_PRICE': 5,
        'MAX_ENTRY_PRICE': 55,
        'MIN_CONTRACTS': 2,
        'MAX_CONTRACTS_CEILING': 25,
        'KELLY_TYPE': 'conviction',  # |win_prob - 0.5| * KELLY_FRACTION
        'ADAPTIVE_PENALTY_BASE': 0.0,  # did not exist
        'ADAPTIVE_PENALTY_MAX': 0.0,   # did not exist
        'PERF_MAX_ADJUSTMENT': 0.0,    # did not exist
        'REGIME_GATE_ENABLED': False,   # did not exist
        'REQUIRE_SIGNAL_AGREEMENT': False,  # was a soft gate, not hard
        'BASE_RISK_PCT': 0.015,
        'STRONG_RISK_PCT': 0.035,
        'WEAK_RISK_PCT': 0.020,
    },
    'era10': {
        'description': 'EV-first architecture: entry band 38-49c, payoff Kelly. -$7.57, 12.5% WR',
        'MIN_CONVICTION_THRESHOLD': 0.010,
        'MIN_ENTRY_PRICE': 38,
        'MAX_ENTRY_PRICE': 49,
        'MIN_CONTRACTS': 1,
        'MAX_CONTRACTS_CEILING': 25,
        'KELLY_TYPE': 'payoff_aware',  # (b*p - q) / b where b = payout/cost
        'ADAPTIVE_PENALTY_BASE': 0.005,
        'ADAPTIVE_PENALTY_MAX': 0.02,
        'PERF_MAX_ADJUSTMENT': 0.02,
        'REGIME_GATE_ENABLED': True,
        'REGIME_LEARNING_ENABLED': True,
        'ASSET_SIZING_LEARNING_ENABLED': True,
        'REQUIRE_SIGNAL_AGREEMENT': False,
        'BASE_RISK_PCT': 0.015,
        'IDEAL_ENTRY_MIN': 42,
        'IDEAL_ENTRY_MAX': 47,
        'MIN_ADJUSTED_EV': -2.0,
    },
    'era11': {
        'description': 'Era 2 redux with Era 10 logging. Gates open, max 5 contracts. -$3.38, 30% WR',
        'MIN_CONVICTION_THRESHOLD': 0.001,
        'MIN_ENTRY_PRICE': 15,
        'MAX_ENTRY_PRICE': 55,
        'MIN_CONTRACTS': 1,
        'MAX_CONTRACTS_CEILING': 5,
        'KELLY_TYPE': 'payoff_aware',  # still had payoff Kelly (bug)
        'ADAPTIVE_PENALTY_BASE': 0.005,  # still active (bug — biased NO)
        'ADAPTIVE_PENALTY_MAX': 0.02,
        'PERF_MAX_ADJUSTMENT': 0.02,    # still active (bug — reinforced losses)
        'REGIME_GATE_ENABLED': False,
        'REGIME_LEARNING_ENABLED': False,
        'ASSET_SIZING_LEARNING_ENABLED': False,
        'REQUIRE_SIGNAL_AGREEMENT': False,
        'BASE_RISK_PCT': 0.015,
        'MIN_ADJUSTED_EV': -10.0,
    },
    'era12': {
        'description': 'Pure Era 2 restoration with Era 10 logging. Balance: $54.16',
        'MIN_CONVICTION_THRESHOLD': 0.01,
        'MIN_ENTRY_PRICE': 5,
        'MAX_ENTRY_PRICE': 55,
        'MIN_CONTRACTS': 2,
        'MAX_CONTRACTS_CEILING': 10,  # reduced from Era 2s 25 for safety
        'KELLY_TYPE': 'conviction',   # |win_prob - 0.5| * KELLY_FRACTION
        'ADAPTIVE_PENALTY_BASE': 0.0,
        'ADAPTIVE_PENALTY_MAX': 0.0,
        'PERF_MAX_ADJUSTMENT': 0.0,
        'REGIME_GATE_ENABLED': False,
        'REGIME_LEARNING_ENABLED': False,
        'ASSET_SIZING_LEARNING_ENABLED': False,
        'REQUIRE_SIGNAL_AGREEMENT': False,
        'BASE_RISK_PCT': 0.015,
        'STRONG_RISK_PCT': 0.035,
        'WEAK_RISK_PCT': 0.020,
    },
    'era13': {
        'description': 'Sniper Mode: 41-47c only, no XRP, max 5 contracts. Balance: $54.16',
        'CRYPTO_15MIN_SERIES': ['KXBTC15M', 'KXETH15M', 'KXSOL15M'],  # dropped XRP
        'MIN_CONVICTION_THRESHOLD': 0.01,
        'MIN_ENTRY_PRICE': 41,
        'MAX_ENTRY_PRICE': 47,
        'MIN_CONTRACTS': 2,
        'MAX_CONTRACTS_CEILING': 5,
        'KELLY_TYPE': 'conviction',
        'ADAPTIVE_PENALTY_BASE': 0.0,
        'ADAPTIVE_PENALTY_MAX': 0.0,
        'PERF_MAX_ADJUSTMENT': 0.0,
        'REGIME_GATE_ENABLED': False,
        'REGIME_LEARNING_ENABLED': False,
        'ASSET_SIZING_LEARNING_ENABLED': False,
        'REQUIRE_SIGNAL_AGREEMENT': False,
        'BASE_RISK_PCT': 0.015,
        'STRONG_RISK_PCT': 0.035,
        'WEAK_RISK_PCT': 0.020,
    },
    'era14': {
        'description': 'Era 2 revival: widen to 41-55c, add XRP back, max 10 contracts. Balance: $53',
        'CRYPTO_15MIN_SERIES': ['KXBTC15M', 'KXETH15M', 'KXSOL15M', 'KXXRP15M'],
        'MIN_CONVICTION_THRESHOLD': 0.01,
        'MIN_ENTRY_PRICE': 41,
        'MAX_ENTRY_PRICE': 55,
        'MIN_CONTRACTS': 2,
        'MAX_CONTRACTS_CEILING': 10,
        'KELLY_TYPE': 'conviction',
        'ADAPTIVE_PENALTY_BASE': 0.0,
        'ADAPTIVE_PENALTY_MAX': 0.0,
        'PERF_MAX_ADJUSTMENT': 0.0,
        'REGIME_GATE_ENABLED': False,
        'REGIME_LEARNING_ENABLED': False,
        'ASSET_SIZING_LEARNING_ENABLED': False,
        'REQUIRE_SIGNAL_AGREEMENT': False,
        'BASE_RISK_PCT': 0.015,
        'STRONG_RISK_PCT': 0.035,
        'WEAK_RISK_PCT': 0.020,
    },
    'era15': {
        'description': 'Signal purge: Signal E killed (0.0), Signal D neutered (0.15→0.05). Observation mode.',
        'CRYPTO_15MIN_SERIES': ['KXBTC15M', 'KXETH15M', 'KXSOL15M', 'KXXRP15M'],
        'MIN_CONVICTION_THRESHOLD': 0.01,
        'MIN_ENTRY_PRICE': 41,
        'MAX_ENTRY_PRICE': 55,
        'MIN_CONTRACTS': 2,
        'MAX_CONTRACTS_CEILING': 10,
        'KELLY_TYPE': 'conviction',
        'SIGNAL_TREND_WEIGHT': 0.0,
        'SIGNAL_CONVERGENCE_WEIGHT': 0.05,
        'ADAPTIVE_PENALTY_BASE': 0.0,
        'ADAPTIVE_PENALTY_MAX': 0.0,
        'PERF_MAX_ADJUSTMENT': 0.0,
        'REGIME_GATE_ENABLED': False,
        'REQUIRE_SIGNAL_AGREEMENT': False,
        'BASE_RISK_PCT': 0.015,
        'STRONG_RISK_PCT': 0.035,
        'WEAK_RISK_PCT': 0.020,
        'OBSERVATION_MODE': True,
    },
    'era16': {
        'description': 'Asymmetric Dollar Edge: 44-52c band, payoff ratio gate. Balance: $49.22',
        'CRYPTO_15MIN_SERIES': ['KXBTC15M', 'KXETH15M', 'KXSOL15M', 'KXXRP15M'],
        'MIN_CONVICTION_THRESHOLD': 0.01,
        'MIN_ENTRY_PRICE': 44,
        'MAX_ENTRY_PRICE': 53,
        'MIN_CONTRACTS': 2,
        'MAX_CONTRACTS_CEILING': 10,
        'KELLY_TYPE': 'conviction',
        'SIGNAL_TREND_WEIGHT': 0.0,
        'SIGNAL_CONVERGENCE_WEIGHT': 0.05,
        'MIN_PAYOFF_RATIO': 1.0,
        'ADAPTIVE_PENALTY_BASE': 0.0,
        'ADAPTIVE_PENALTY_MAX': 0.0,
        'PERF_MAX_ADJUSTMENT': 0.0,
        'REGIME_GATE_ENABLED': False,
        'REQUIRE_SIGNAL_AGREEMENT': False,
        'BASE_RISK_PCT': 0.015,
        'STRONG_RISK_PCT': 0.035,
        'WEAK_RISK_PCT': 0.020,
        'IDEAL_ENTRY_MIN': 44,
        'IDEAL_ENTRY_MAX': 46,
        'OBSERVATION_MODE': True,
    },
    'era17': {
        'description': 'Dumb Money: cheaper-side direction, fixed 3 contracts, 44-53c band. Balance: $49.22',
        'CRYPTO_15MIN_SERIES': ['KXBTC15M', 'KXETH15M', 'KXSOL15M', 'KXXRP15M'],
        'CHEAP_SIDE_MODE': True,
        'MIN_ENTRY_PRICE': 44,
        'MAX_ENTRY_PRICE': 53,
        'MIN_PAYOFF_RATIO': 1.0,
        'MIN_CONTRACTS': 2,
        'MAX_CONTRACTS_CEILING': 10,
        'SIGNAL_TREND_WEIGHT': 0.0,
        'SIGNAL_CONVERGENCE_WEIGHT': 0.05,
        'ADAPTIVE_PENALTY_BASE': 0.0,
        'ADAPTIVE_PENALTY_MAX': 0.0,
        'PERF_MAX_ADJUSTMENT': 0.0,
        'REGIME_GATE_ENABLED': False,
        'REQUIRE_SIGNAL_AGREEMENT': False,
        'IDEAL_ENTRY_MIN': 44,
        'IDEAL_ENTRY_MAX': 46,
        'OBSERVATION_MODE': True,
        'FIXED_CONTRACTS': 3,
        'NOTE': 'Direction by cheaper side, gates 3+4 bypassed, signal still logged for comparison',
    },
    'era18': {
        'description': 'Smart Dumb Money: signal veto + 44-49c band. Balance: $49.22',
        'CRYPTO_15MIN_SERIES': ['KXBTC15M', 'KXETH15M', 'KXSOL15M', 'KXXRP15M'],
        'CHEAP_SIDE_MODE': True,
        'SIGNAL_VETO_ENABLED': True,
        'MIN_ENTRY_PRICE': 44,
        'MAX_ENTRY_PRICE': 50,
        'MIN_PAYOFF_RATIO': 1.0,
        'MIN_CONTRACTS': 2,
        'MAX_CONTRACTS_CEILING': 10,
        'SIGNAL_TREND_WEIGHT': 0.0,
        'SIGNAL_CONVERGENCE_WEIGHT': 0.05,
        'ADAPTIVE_PENALTY_BASE': 0.0,
        'ADAPTIVE_PENALTY_MAX': 0.0,
        'PERF_MAX_ADJUSTMENT': 0.0,
        'REGIME_GATE_ENABLED': False,
        'REQUIRE_SIGNAL_AGREEMENT': False,
        'IDEAL_ENTRY_MIN': 44,
        'IDEAL_ENTRY_MAX': 46,
        'OBSERVATION_MODE': True,
        'FIXED_CONTRACTS': 3,
        'NOTE': 'Cheap-side direction + signal veto (29.4% WR when disagree). 50c blocked (41.8% WR, -$22.50).',
    },
    'era19': {
        'description': 'YES Only: structural YES bias edge. YES 49.9% vs NO 36.6% on 880 Era 18 trades.',
        'CRYPTO_15MIN_SERIES': ['KXBTC15M', 'KXETH15M', 'KXSOL15M', 'KXXRP15M'],
        'YES_ONLY_MODE': True,
        'CHEAP_SIDE_MODE': True,  # fallback if YES_ONLY_MODE disabled
        'SIGNAL_VETO_ENABLED': False,  # not needed — no NO picks to veto
        'MIN_ENTRY_PRICE': 44,
        'MAX_ENTRY_PRICE': 55,  # expanded — YES at 50-55c had 54-58% would-have-won
        'MIN_PAYOFF_RATIO': 1.0,
        'MIN_CONTRACTS': 2,
        'MAX_CONTRACTS_CEILING': 10,
        'SIGNAL_TREND_WEIGHT': 0.0,
        'SIGNAL_CONVERGENCE_WEIGHT': 0.05,
        'ADAPTIVE_PENALTY_BASE': 0.0,
        'ADAPTIVE_PENALTY_MAX': 0.0,
        'PERF_MAX_ADJUSTMENT': 0.0,
        'REGIME_GATE_ENABLED': False,
        'REQUIRE_SIGNAL_AGREEMENT': False,
        'IDEAL_ENTRY_MIN': 44,
        'IDEAL_ENTRY_MAX': 46,
        'OBSERVATION_MODE': True,
        'FIXED_CONTRACTS': 3,
        'NOTE': 'Always YES direction. YES settles 53%+ structurally. Ceiling expanded to 55c.',
    },
    'era20': {
        'description': 'Tight Spread Cheap Side: directionally agnostic, spread ≤3c, 46-50c band.',
        'CRYPTO_15MIN_SERIES': ['KXBTC15M', 'KXETH15M', 'KXSOL15M', 'KXXRP15M'],
        'YES_ONLY_MODE': False,
        'CHEAP_SIDE_MODE': True,
        'SIGNAL_VETO_ENABLED': False,
        'MAX_SPREAD': 3,  # only trade when |YES_ask - NO_ask| <= 3c
        'MIN_ENTRY_PRICE': 46,
        'MAX_ENTRY_PRICE': 50,
        'MIN_PAYOFF_RATIO': 1.0,
        'OBSERVATION_MODE': True,
        'FIXED_CONTRACTS': 3,
        'NOTE': 'Directionally agnostic. Tight spread = market indecision = cheap side edge. 50.7% WR on 663 signals.',
    },
}
